# Usar una imagen base de OpenJDK 17
FROM openjdk:17-jdk-slim

# Configurar el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo JAR generado al contenedor
COPY target/backendproyecto-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto que usará tu aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
