# Usar una imagen base de OpenJDK 17
FROM eclipse-temurin:17.0.13_11-jre

# Exponer el puerto que usará tu aplicación
EXPOSE 8080

#DEFINIR DIRECTORIO RAIZ DE NUESTRO CONTENEDOR
WORKDIR /root


# COPIAR Y PEGAR ARCHIVOS DENTRO DEL CONTENEDOR
COPY ./pom.xml /root/
COPY ./.mvn /root/.mvn 
COPY ./mvnw /root/


#DESCARGAR LAS DEPENDECIAS
RUN ./mvnw dependency:go-offline


#COPIAR EL CODIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /root/src


RUN ./mvn clean install -DskipTests

#LEVANTAR NUESTRA APLICACION INICIE
ENTRYPOINT ["java", "-jar", "/root/target/SpringDocker-0.0.1-SNAPSHOT.jar"]


